Repository knative/build-templates, pull requests merged in 2018-08, with the labels that each got.

#50 buildah: successful build template
  buildah/Dockerfile
  buildah/buildah.yaml
Labels: approved, lgtm, size/S

#7 Add buildah builder
  buildah/Dockerfile
  buildah/README.md
  buildah/buildah.yaml
Labels: approved, size/L

#53 Specify workingDir instead of workingdir in buildpack build template
  buildpack/buildpack.yaml
Labels: approved, lgtm, size/XS

#55 Adding a note about Build Template kind
  README.md
Labels: approved, lgtm, size/S

#56 Fail fast in update-deps.sh when sourcing library.sh
  hack/update-deps.sh
Labels: approved, lgtm, size/XS

#54 buildah: better out-of-the-gate usage
  buildah/Dockerfile
  buildah/README.md
  buildah/buildah.yaml
Labels: approved, lgtm, size/S

#57 buildah: quotes for string, not a bool
  buildah/buildah.yaml
Labels: approved, lgtm, size/XS
