Repository knative/build-templates, pull requests merged in 2018-09, with the labels that each got.

#62 Update test-infra dependency
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
Labels: approved, lgtm, size/L

#59 Fully-qualifies jib-maven-plugin invocation.
  jib/jib-maven.yaml
Labels: approved, lgtm, size/XS

#60 Adds DIRECTORY parameter to Jib templates to configure a subdirectory within the source.
  jib/jib-gradle.yaml
  jib/jib-maven.yaml
Labels: approved, lgtm, size/XS

#66 Updates Jib template README with new parameters.
  jib/README.md
Labels: approved, lgtm, needs-ok-to-test, size/M

#64 Adds CACHE to Jib templates to make builds run faster.
  jib/README.md
  jib/jib-gradle.yaml
  jib/jib-maven.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L
