Repository knative/build-templates, pull requests merged in 2019-04, with the labels that each got.

#102 Install Knative Build for E2E tests from the right place
  Gopkg.lock
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#82 Optionally add pull secret for private ECR
  ecr_helper/README.md
  ecr_helper/helper.sh
Labels: approved, lgtm, size/M

#108 buildah: ensure final image has updates
  buildah/Dockerfile
Labels: approved, lgtm, size/XS

#111 update test-infra: allow handling stock out with retries
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
Labels: approved, lgtm, size/L

#109 buildkit: update to v0.4.0 (securityContext no longer needed)
  buildkit/0-buildkitd.yaml
  buildkit/1-buildtemplate.yaml
  buildkit/README.md
Labels: approved, lgtm, ok-to-test, size/M
