Repository knative/build-templates, pull requests merged in 2019-05, with the labels that each got.

#114 Fix typo in readme
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#115 Update test-infra: handle stockout to work with new error string
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/L

#118 Update OWNERS to use OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
  test/OWNERS
Labels: approved, lgtm, size/M
