Repository knative/build-templates, pull requests merged in 2019-01, with the labels that each got.

#83 Add flag to disable the use of credential helpers
  buildpack/README.md
  buildpack/buildpack.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#84 Add real build presubmit tests
  Gopkg.lock
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#86 Pin to kaniko v0.1.0
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#87 Explicitly set DOCKER_CONFIG in the kaniko build template.
  kaniko/kaniko.yaml
Labels: approved, lgtm, size/XS

#81 Unset IFS to avoid quoting issues
  ecr_helper/helper.sh
Labels: approved, lgtm, size/XS
