Repository knative/build-templates, pull requests merged in 2019-02, with the labels that each got.

#74 buildah: convert Dockerfile to a multi-stage build
  buildah/Dockerfile
  buildah/README.md
Labels: approved, lgtm, size/M

#91 update deps:test-infra for fixing release.yaml not found error
  Gopkg.lock
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
Labels: approved, lgtm, size/XL

#96 buildah: gophers and yams 🥔
  buildah/Dockerfile
Labels: approved, lgtm, size/XS
